Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: br.com.ldf.medium.function.UppercaseFunction
      CodeUri: /home/lucas_fernandes/git/projects/personal/spring-cloud-function-aws
      Runtime: java21
      Architectures:
        - x86_64